version: 2.1

orbs:
  node: circleci/node@5

jobs:
  lint:
    docker:
      - image: cimg/node:20.11.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run lint
          command: npm run lint

  test:
    docker:
      - image: cimg/node:20.11.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test

  build-node:
    docker:
      - image: cimg/node:20.11.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npm run build

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - build-node:
          requires:
            - test
